// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtxugvxokjhiiulllmeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eHVndnhva2poaWl1bGxsbWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjA0NjgsImV4cCI6MjA2ODEzNjQ2OH0.ZQ3Fej7rWC_vNvsG7WodY4a16eA6AgQ5hTd_65GdAc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});